### ISSUE TITLE
FrameBox fontSize option is ignored. 

### ISSUE THREAD

**Issue by Miesvanderlippe** [faressoft/terminalizer#105]
I'm trying to create a render for bigger screens and I'm failing to size the title of the terminal. 

I've tried both values in px and in just integers. I figured I'd also set the lineHeight but that doesn't seem to impact anything either. I've tried searching the code but I'm not seeing anything obvious. 

Here's what I'm trying right now; 
```yml
frameBox:
  type: floating
  title: whoami
  height: 100
  style:
    border: 0px black solid
    # boxShadow: none
    margin: 3px
    lineHeight: 130
    fontSize: 100
  ```

Please do tell me if rendering a bigger terminal header is possible. 

If supporting a scale factor is an option, please do add that. I'd love to just render it at 2x the resolution so I don't need to scale separate elements.
