### ISSUE TITLE
Renderer inconsistently renders the hostname of this recording. 

### ISSUE THREAD

**Issue by Miesvanderlippe** [faressoft/terminalizer#106]
I'm rendering a few terminals but I've found some colored text not to be rendered consistently. Sometimes, the hostname in my ZSH recording gets duplicated but other times (with the exact same input) it doesn't. 

Relevant lines from the recording:
```yml
# Records, feel free to edit them
records:
  - delay: 391
    content: "\e]0;\a\e[01;32m[dennis@nfir\e[01;37m profiles\e[01;32m]$\e[00m "
  - delay: 100
```
Duplicated output:
![Screenshot from 2020-05-26 12-23-54](https://user-images.githubusercontent.com/5888605/82890258-2e386480-9f4c-11ea-9f25-75513da3849a.png)
Regular output:
![Screenshot from 2020-05-26 12-26-13](https://user-images.githubusercontent.com/5888605/82890262-2f699180-9f4c-11ea-8345-73a6cc4b0ff4.png)

The entire input file hasn't changed, neither has the config or the render command. 

It also happened with the original recording (with the same inconsitency) so I had taken out the duplicate text. Here's the original recording:
```yml
records:
  - delay: 311
    content: "\e]0;miesl@mies-pc:~/-censored path-\a\e[01;32m[miesl@mies-pc\e[01;37m -censored directory-\e[01;32m]$\e[00m "

```
