### ISSUE TITLE
How to put a watermark at the top right corner?

### ISSUE THREAD

**Issue by rsalmei** [faressoft/terminalizer#130]
My watermark is currently as your example in the readme, at the bottom right corner:
```
  watermark:
    imagePath: /path/image.png
    style:
      position: absolute
      right: 15px
      bottom: 0px
      width: 100px
      opacity: 0.2
```

But I'd like to position it at the top right corner. How could I do that?
Looking in the internet, it seems the parent content should use relative positioning and the image absolute. But it already uses absolute... It seems some inner content should be relative, would that be possible?

Example from [stack overflow](https://stackoverflow.com/questions/7282236/placing-an-image-to-the-top-right-corner-css):
```html
#content {
    position: relative;
}
#content img {
    position: absolute;
    top: 0px;
    right: 0px;
}

<div id="content">
    <img src="images/ribbon.png" class="ribbon"/>
    <div>some text...</div>
</div
```
