### ISSUE TITLE
When setting frameBox / Title,  two command prompts are shown

### ISSUE THREAD

**Issue by lukehinds** [faressoft/terminalizer#171]
```
frameBox:
  type: floating # same for window
  title: Ter
  style:
    border: 0px black solid
    # boxShadow: none
    # margin: 0px
```

![render1623674174195](https://user-images.githubusercontent.com/7058938/121893740-3d847e80-cd16-11eb-921e-ed55667e1ffd.gif)
