### ISSUE TITLE
Seems like delays are shifted in generated GIF

### ISSUE THREAD

**Issue by cdlm** [faressoft/terminalizer#22]
In the GIF rendering, delays happen after the matching content is displayed instead of before as in terminal replays.

This results in glitches such as the first letter of every command being shown quickly after the prompt, then the rest comes after the _"I'll wait a bit before starting to type the next command"_ pause, or the screen being cleared too fast and staying blank for a delay that was intended to be before the clear…

This is easy to confirm with events like so (for me they play as _X-dash… X_ in the terminal, and _X… dash-X_ in the GIF):
```yaml
records:
  - delay: 1000
    content: " X"
  - delay: 100
    content: " -"
  - delay: 1000
    content: " X"
```
