### ISSUE TITLE
Render on small recording taking over 30 minutes

### ISSUE THREAD

**Issue by trevordmiller** [faressoft/terminalizer#28]
I have a small 200 line recording (included at the bottom) where I was testing terminalizer which was recorded using this command:

```shell
terminalizer record ./src/static/some-recording.yml --config terminalizerrc.yml
```

I am using the following command to render it to a gif:

```shell
terminalizer render ./src/static/some-recording.yml --output ./src/static/some-recording.gif
```

![image](https://user-images.githubusercontent.com/5497885/44937269-a8b36080-ad35-11e8-82e7-c95745ac4745.png)

I'm on version `0.2.11`, installed with `npm install -g terminalizer`

![image](https://user-images.githubusercontent.com/5497885/44937150-23c84700-ad35-11e8-8c51-ee40979ad131.png)

I'm on a mac, latest stable version.

I finally killed the process after 30 minutes. Any idea why it would be taking so long?

---

# some-recording.yml

```yaml
# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: bash -l
  
  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /Users/trevordmiller/repos/slides-starter
  
  # Export additional ENV variables
  env:
    recording: true
  
  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 280
  
  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 71
  
  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: -1
  
  # Quality
  # 1 - 100
  quality: 100
  
  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto
  
  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: 2000
  
  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: null
    title: null
    style:
      backgroundColor: black
  
  # Add a watermark image to the rendered gif
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9
  
  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block
  
  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "monospace"
  
  # The size of the font
  fontSize: 32
  
  # The height of lines
  lineHeight: 1
  
  # The spacing between letters
  letterSpacing: 0
  
  # Theme
  theme:
    background: "transparent"
    foreground: "#C5D4DD"
    cursor: "#7FC1CA"
    black: "#3C4C55"
    red: "#DF8C8C"
    green: "#A8CE93"
    yellow: "#DADA93"
    blue: "#83AFE5"
    magenta: "#9A93E1"
    cyan: "#7FC1CA"
    white: "#C5D4DD"
    brightBlack: "#899BA6"
    brightRed: "#F2C38F"
    brightGreen: "#A8CE93"
    brightYellow: "#DADA93"
    brightBlue: "#83AFE5"
    brightMagenta: "#D18EC2"
    brightCyan: "#7FC1CA"
    brightWhite: "#E6EEF3"
  
# Records, feel free to edit them
records:
  - delay: 904
    content: "\r\r\n\e[01;36mslides-starter\r\r\n\e[01;33m$\e[0m "
  - delay: 3585
    content: e
  - delay: 158
    content: c
  - delay: 66
    content: h
  - delay: 81
    content: o
  - delay: 146
    content: ' '
  - delay: 225
    content: '"'
  - delay: 562
    content: S
  - delay: 135
    content: o
  - delay: 56
    content: m
  - delay: 124
    content: e
  - delay: 90
    content: ' '
  - delay: 79
    content: e
  - delay: 158
    content: x
  - delay: 33
    content: a
  - delay: 89
    content: m
  - delay: 48
    content: p
  - delay: 54
    content: l
  - delay: 192
    content: e
  - delay: 461
    content: ' '
  - delay: 79
    content: r
  - delay: 56
    content: e
  - delay: 158
    content: c
  - delay: 315
    content: o
  - delay: 123
    content: r
  - delay: 66
    content: d
  - delay: 103
    content: i
  - delay: 45
    content: 'n'
  - delay: 79
    content: g
  - delay: 169
    content: '"'
  - delay: 427
    content: "\r\nSome example recording\r\n\r\r\n\e[01;36mslides-starter\r\r\n\e[01;33m$\e[0m "
  - delay: 10305
    content: g
  - delay: 71
    content: i
  - delay: 131
    content: t
  - delay: 90
    content: ' '
  - delay: 157
    content: s
  - delay: 56
    content: t
  - delay: 68
    content: a
  - delay: 56
    content: t
  - delay: 102
    content: u
  - delay: 90
    content: s
  - delay: 551
    content: "\r\n"
  - delay: 17
    content: "\e[1;30m\e[m\e[1;30mOn branch \e[m\e[36mmaster\e[m\r\n\e[1;30mYour branch is up to date with 'origin/master'.\e[m\r\n\r\n\e[1;30mChanges to be committed:\e[m\r\n\e[1;30m  (use \"git reset HEAD <file>...\" to unstage)\e[m\r\n\e[1;30m\e[m\r\n\e[1;30m\t\e[m\e[32mmodified:   .lintstagedrc.json\e[m\r\n\e[1;30m\t\e[m\e[32mmodified:   contributing.md\e[m\r\n\e[1;30m\t\e[m\e[32mmodified:   package.json\e[m\r\n\e[1;30m\t\e[m\e[32mmodified:   src/index.mdx\e[m\r\n\e[1;30m\t\e[m\e[32mdeleted:    src/static/some-image.gif\e[m\r\n\e[1;30m\t\e[m\e[32mnew file:   terminalizerrc.yml\e[m\r\n\e[1;30m\e[m\r\n\e[1;30mUntracked files:\e[m\r\n\e[1;30m  (use \"git add <file>...\" to include in what will be committed)\e[m\r\n\e[1;30m\e[m\r\n\e[1;30m\t\e[36msrc/static/\e[m\r\n\r\n\r\r\n\e[01;36mslides-starter\r\r\n\e[01;33m$\e[0m "
  - delay: 7733
    content: "logout\r\n"
```

# terminalizerrc.yml

```yaml
# Specify a command to be executed
# like `/bin/bash -l`, `ls`, or any other commands
# the default is bash for Linux
# or powershell.exe for Windows
command: null

# Specify the current working directory path
# the default is the current working directory path
cwd: null

# Export additional ENV variables
env:
  recording: true

# Explicitly set the number of columns
# or use `auto` to take the current
# number of columns of your shell
cols: auto

# Explicitly set the number of rows
# or use `auto` to take the current
# number of rows of your shell
rows: auto

# Amount of times to repeat GIF
# If value is -1, play once
# If value is 0, loop indefinitely
# If value is a positive number, loop n times
repeat: -1

# Quality
# 1 - 100
quality: 100

# Delay between frames in ms
# If the value is `auto` use the actual recording delays
frameDelay: auto

# Maximum delay between frames in ms
# Ignored if the `frameDelay` isn't set to `auto`
# Set to `auto` to prevent limiting the max idle time
maxIdleTime: 2000

# The surrounding frame box
# The `type` can be null, window, floating, or solid`
# To hide the title use the value null
# Don't forget to add a backgroundColor style with a null as type
frameBox:
  type: null
  title: null
  style:
    backgroundColor: black

# Add a watermark image to the rendered gif
# You need to specify an absolute path for
# the image on your machine or a URL, and you can also
# add your own CSS styles
watermark:
  imagePath: null
  style:
    position: absolute
    right: 15px
    bottom: 15px
    width: 100px
    opacity: 0.9

# Cursor style can be one of
# `block`, `underline`, or `bar`
cursorStyle: block

# Font family
# You can use any font that is installed on your machine
# in CSS-like syntax
fontFamily: "monospace"

# The size of the font
fontSize: 32

# The height of lines
lineHeight: 1

# The spacing between letters
letterSpacing: 0

# Theme
theme:
  background: "transparent"
  foreground: "#C5D4DD"
  cursor: "#7FC1CA"
  black: "#3C4C55"
  red: "#DF8C8C"
  green: "#A8CE93"
  yellow: "#DADA93"
  blue: "#83AFE5"
  magenta: "#9A93E1"
  cyan: "#7FC1CA"
  white: "#C5D4DD"
  brightBlack: "#899BA6"
  brightRed: "#F2C38F"
  brightGreen: "#A8CE93"
  brightYellow: "#DADA93"
  brightBlue: "#83AFE5"
  brightMagenta: "#D18EC2"
  brightCyan: "#7FC1CA"
  brightWhite: "#E6EEF3"
```

**Comment by faressoft** [comment]
You are recording a terminal with 280 cols and 71 rows and font size of 32 px that equals to 5320 × 2627 px !!!

It is not reasonable to generate that large images.

I changed the configs to

```
# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: bash -l
  
  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /Users/trevordmiller/repos/slides-starter
  
  # Export additional ENV variables
  env:
    recording: true
  
  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 100
  
  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 30
  
  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: -1
  
  # Quality
  # 1 - 100
  quality: 100
  
  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto
  
  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: 2000
  
  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: null
    title: null
    style:
      backgroundColor: black
  
  # Add a watermark image to the rendered gif
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9
  
  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block
  
  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "monospace"
  
  # The size of the font
  fontSize: 12
  
  # The height of lines
  lineHeight: 1
  
  # The spacing between letters
  letterSpacing: 0
  
  # Theme
  theme:
    background: "transparent"
    foreground: "#C5D4DD"
    cursor: "#7FC1CA"
    black: "#3C4C55"
    red: "#DF8C8C"
    green: "#A8CE93"
    yellow: "#DADA93"
    blue: "#83AFE5"
    magenta: "#9A93E1"
    cyan: "#7FC1CA"
    white: "#C5D4DD"
    brightBlack: "#899BA6"
    brightRed: "#F2C38F"
    brightGreen: "#A8CE93"
    brightYellow: "#DADA93"
    brightBlue: "#83AFE5"
    brightMagenta: "#D18EC2"
    brightCyan: "#7FC1CA"
    brightWhite: "#E6EEF3"
  
# Records, feel free to edit them
records:
  - delay: 904
    content: "\r\r\n\e[01;36mslides-starter\r\r\n\e[01;33m$\e[0m "
  - delay: 3585
    content: e
  - delay: 158
    content: c
  - delay: 66
    content: h
  - delay: 81
    content: o
  - delay: 146
    content: ' '
  - delay: 225
    content: '"'
  - delay: 562
    content: S
  - delay: 135
    content: o
  - delay: 56
    content: m
  - delay: 124
    content: e
  - delay: 90
    content: ' '
  - delay: 79
    content: e
  - delay: 158
    content: x
  - delay: 33
    content: a
  - delay: 89
    content: m
  - delay: 48
    content: p
  - delay: 54
    content: l
  - delay: 192
    content: e
  - delay: 461
    content: ' '
  - delay: 79
    content: r
  - delay: 56
    content: e
  - delay: 158
    content: c
  - delay: 315
    content: o
  - delay: 123
    content: r
  - delay: 66
    content: d
  - delay: 103
    content: i
  - delay: 45
    content: 'n'
  - delay: 79
    content: g
  - delay: 169
    content: '"'
  - delay: 427
    content: "\r\nSome example recording\r\n\r\r\n\e[01;36mslides-starter\r\r\n\e[01;33m$\e[0m "
  - delay: 10305
    content: g
  - delay: 71
    content: i
  - delay: 131
    content: t
  - delay: 90
    content: ' '
  - delay: 157
    content: s
  - delay: 56
    content: t
  - delay: 68
    content: a
  - delay: 56
    content: t
  - delay: 102
    content: u
  - delay: 90
    content: s
  - delay: 551
    content: "\r\n"
  - delay: 17
    content: "\e[1;30m\e[m\e[1;30mOn branch \e[m\e[36mmaster\e[m\r\n\e[1;30mYour branch is up to date with 'origin/master'.\e[m\r\n\r\n\e[1;30mChanges to be committed:\e[m\r\n\e[1;30m  (use \"git reset HEAD <file>...\" to unstage)\e[m\r\n\e[1;30m\e[m\r\n\e[1;30m\t\e[m\e[32mmodified:   .lintstagedrc.json\e[m\r\n\e[1;30m\t\e[m\e[32mmodified:   contributing.md\e[m\r\n\e[1;30m\t\e[m\e[32mmodified:   package.json\e[m\r\n\e[1;30m\t\e[m\e[32mmodified:   src/index.mdx\e[m\r\n\e[1;30m\t\e[m\e[32mdeleted:    src/static/some-image.gif\e[m\r\n\e[1;30m\t\e[m\e[32mnew file:   terminalizerrc.yml\e[m\r\n\e[1;30m\e[m\r\n\e[1;30mUntracked files:\e[m\r\n\e[1;30m  (use \"git add <file>...\" to include in what will be committed)\e[m\r\n\e[1;30m\e[m\r\n\e[1;30m\t\e[36msrc/static/\e[m\r\n\r\n\r\r\n\e[01;36mslides-starter\r\r\n\e[01;33m$\e[0m "
  - delay: 7733
    content: "logout\r\n"
```

And it works just fine.

![render1535809434884](https://user-images.githubusercontent.com/1908658/44946529-70c81e00-ae06-11e8-8646-5a57413b76e8.gif)
