### ISSUE TITLE
Render Gets Stuck on 24%

### ISSUE THREAD

**Issue by mohnjatthews** [faressoft/terminalizer#35]
I'm running into an issue where `terminalizer render file_name` stops rendering at 39 frames (24%):

```bash
Rendering frame 39/159 24% [=======-----------------------] 14.4s^C
me@local:$  
me@local:$ terminalizer render high_baller_intro
Rendering frame 39/159 24% [=======-----------------------] 12.0s^C
me@local:$  
me@local:$ terminalizer render high_baller_intro
Rendering frame 39/159 24% [=======-----------------------] 11.8s
me@local:$  
me@local:$ terminalizer render high_baller_intro.yml 
Rendering frame 39/159 24% [=======-----------------------] 12.1s^C
me@local:$  
me@local:$ terminalizer render high_baller_intro.yml 
Rendering frame 39/159 24% [=======-----------------------] 11.8s^C
me@local:$
```

I've checked a few other issues here on Github and I can't seem to find a common cause. Here's my `.yml` file:

```yml
# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: bash -l
  
  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /Users/john/aion_web3
  
  # Export additional ENV variables
  env:
    recording: true
  
  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 80
  
  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 24
  
  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: 0
  
  # Quality
  # 1 - 100
  quality: 100
  
  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto
  
  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: 2000
  
  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: floating
    title: Terminalizer
    style:
      border: 0px black solid
      # boxShadow: none
      # margin: 0px
  
  # Add a watermark image to the rendered gif
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9
  
  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block
  
  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"
  
  # The size of the font
  fontSize: 12
  
  # The height of lines
  lineHeight: 1
  
  # The spacing between letters
  letterSpacing: 0
  
  # Theme
  theme:
    background: "transparent"
    foreground: "#afafaf"
    cursor: "#c7c7c7"
    black: "#232628"
    red: "#fc4384"
    green: "#b3e33b"
    yellow: "#ffa727"
    blue: "#75dff2"
    magenta: "#ae89fe"
    cyan: "#708387"
    white: "#d5d5d0"
    brightBlack: "#626566"
    brightRed: "#ff7fac"
    brightGreen: "#c8ed71"
    brightYellow: "#ebdf86"
    brightBlue: "#75dff2"
    brightMagenta: "#ae89fe"
    brightCyan: "#b1c6ca"
    brightWhite: "#f9f9f4"
  
# Records, feel free to edit them
records:
  - delay: 1000
    content: 'n'
  - delay: 50
    content: o
  - delay: 50
    content: d
  - delay: 50
    content: e
  - delay: 50
    content: ' '
  - delay: 50
    content: c
  - delay: 50
    content: o
  - delay: 50
    content: 'n'
  - delay: 50
    content: s
  - delay: 50
    content: o
  - delay: 50
    content: l
  - delay: 50
    content: e
  - delay: 50
    content: .
  - delay: 50
    content: j
  - delay: 50
    content: s
  - delay: 50
    content: "\r\n"
  - delay: 100
    content: "Connected to default https://aion-web3-api.example.com\r\n\r\n"
  - delay: 100
    content: "aion-web3-api.example.com> "
  - delay: 1000
    content: c
  - delay: 50
    content: o
  - delay: 50
    content: 'n'
  - delay: 50
    content: s
  - delay: 50
    content: t
  - delay: 50
    content: ' '
  - delay: 50
    content: h
  - delay: 50
    content: i
  - delay: 50
    content: g
  - delay: 50
    content: h
  - delay: 50
    content: _
  - delay: 50
    content: b
  - delay: 50
    content: a
  - delay: 50
    content: l
  - delay: 50
    content: l
  - delay: 50
    content: e
  - delay: 50
    content: r
  - delay: 50
    content: ' '
  - delay: 50
    content: '='
  - delay: 50
    content: ' '
  - delay: 50
    content: "0x..."
  - delay: 50
    content: ''
  - delay: 50
    content: "\r\n\r\n"
  - delay: 100
    content: "[undefined]\r\n\r\n"
  - delay: 100
    content: "aion-web3-api.example.com> "
  - delay: 1000
    content: w
  - delay: 50
    content: e
  - delay: 50
    content: b
  - delay: 50
    content: '3'
  - delay: 50
    content: .
  - delay: 50
    content: e
  - delay: 50
    content: t
  - delay: 50
    content: h
  - delay: 50
    content: .
  - delay: 50
    content: g
  - delay: 50
    content: e
  - delay: 50
    content: t
  - delay: 50
    content: B
  - delay: 50
    content: a
  - delay: 50
    content: l
  - delay: 50
    content: a
  - delay: 50
    content: 'n'
  - delay: 50
    content: c
  - delay: 50
    content: "e"
  - delay: 50
    content: '('
  - delay: 50
    content: 'h'
  - delay: 50
    content: i
  - delay: 50
    content: g
  - delay: 50
    content: h
  - delay: 50
    content: _
  - delay: 50
    content: b
  - delay: 50
    content: a
  - delay: 50
    content: l
  - delay: 50
    content: l
  - delay: 50
    content: e
  - delay: 50
    content: r
  - delay: 50
    content: ','
  - delay: 50
    content: ' '
  - delay: 50
    content: "("
  - delay: 50
    content: e
  - delay: 50
    content: r
  - delay: 50
    content: r
  - delay: 50
    content: ','
  - delay: 50
    content: ' '
  - delay: 50
    content: b
  - delay: 50
    content: a
  - delay: 50
    content: l
  - delay: 50
    content: )
  - delay: 50
    content: ' '
  - delay: 50
    content: =
  - delay: 50
    content: '>'
  - delay: 50
    content: ' '
  - delay: 50
    content: '{'
  - delay: 50
    content: b
  - delay: 50
    content: a
  - delay: 50
    content: l
  - delay: 50
    content: a
  - delay: 50
    content: 'n'
  - delay: 50
    content: c
  - delay: 50
    content: e
  - delay: 50
    content: ' '
  - delay: 50
    content: =
  - delay: 50
    content: ' '
  - delay: 50
    content: b
  - delay: 50
    content: a
  - delay: 50
    content: l
  - delay: 50
    content: '}'
  - delay: 50
    content: )
  - delay: 50
    content: "\r\r\n"
  - delay: 100
    content: "Promise {\r\n  \e[36m<pending>\e[39m,\r\n  domain:\r\n   Domain {\r\n     domain: \e[1mnull\e[22m,\r\n     _events:\r\n      [Object: null prototype] {\r\n        removeListener: \e[36m[Function: updateExceptionCapture]\e[39m,\r\n        newListener: \e[36m[Function: updateExceptionCapture]\e[39m,\r\n        error: \e[36m[Function: debugDomainError]\e[39m },\r\n     _eventsCount: \e[33m3\e[39m,\r\n     _maxListeners: \e[90mundefined\e[39m,\r\n     members: [] } }\r\n"
  - delay: 100
    content: "https://aion-web3-api.example.com> "
  - delay: 1000
    content: b
  - delay: 50
    content: a
  - delay: 50
    content: l
  - delay: 50
    content: a
  - delay: 50
    content: 'n'
  - delay: 50
    content: c
  - delay: 50
    content: e
  - delay: 50
    content: "\r\n44893545833580441025"
  - delay: 50
    content: "\r\nhttps://aion-web3-api.example.com> "
  - delay: 1000
    content: w
  - delay: 50
    content: e
  - delay: 50
    content: b
  - delay: 50
    content: '3'
  - delay: 50
    content: .
  - delay: 50
    content: u
  - delay: 50
    content: t
  - delay: 50
    content: i
  - delay: 50
    content: l
  - delay: 50
    content: s
  - delay: 50
    content: .
  - delay: 50
    content: f
  - delay: 50
    content: r
  - delay: 50
    content: o
  - delay: 50
    content: m
  - delay: 50
    content: 'N'
  - delay: 50
    content: A
  - delay: 50
    content: m
  - delay: 50
    content: p
  - delay: 50
    content: (
  - delay: 50
    content: b
  - delay: 50
    content: a
  - delay: 50
    content: l
  - delay: 50
    content: a
  - delay: 50
    content: 'n'
  - delay: 50
    content: c
  - delay: 50
    content: e
  - delay: 50
    content: ','
  - delay: 50
    content: ' '
  - delay: 50
    content: ''''
  - delay: 50
    content: a
  - delay: 50
    content: i
  - delay: 50
    content: o
  - delay: 50
    content: 'n'
  - delay: 50
    content: ''''
  - delay: 50
    content: )
  - delay: 100
    content: "\r\r\n\e[32m'44.893545833580441025'\r\n"
  - delay: 50
    content: "https://aion-web3-api.example.com> "
  - delay: 952
    content: "logout\r\nSaving session..."
  - delay: 11
    content: "\r\n...saving history..."
  - delay: 6
    content: "truncating history files...\r\n...completed.\r\n"
```

Running V0.4.1 on macOS Mojave (10.14 [18A391]) installed via Brew.
