### ISSUE TITLE
Terminalizer for fish-shell 

### ISSUE THREAD

**Issue by alipiry** [faressoft/terminalizer#44]

**Comment by alipiry** [comment]
It doesn't work with fish-shell!
I have changed `command` in `config.yml`, but it didn't work

**Comment by acomagu** [comment]
It works by `terminalizer record test-fish -d fish` for me but no cursor...
![render1567124654259](https://user-images.githubusercontent.com/1362750/63984992-86028600-cb08-11e9-9edc-32ab854db0de.gif)

<details>
<summary>(With default configurations)</summary>

```
# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: fish
  
  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /home/yuki/.local/src/github.com/acomagu/fish-async-prompt
  
  # Export additional ENV variables
  env:
    recording: true
  
  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 182
  
  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 46
  
  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: 0
  
  # Quality
  # 1 - 100
  quality: 100
  
  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto
  
  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: 2000
  
  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: floating
    title: Terminalizer
    style:
      border: 0px black solid
      # boxShadow: none
      # margin: 0px
  
  # Add a watermark image to the rendered gif
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9
  
  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block
  
  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"
  
  # The size of the font
  fontSize: 12
  
  # The height of lines
  lineHeight: 1
  
  # The spacing between letters
  letterSpacing: 0
  
  # Theme
  theme:
    background: "transparent"
    foreground: "#afafaf"
    cursor: "#c7c7c7"
    black: "#232628"
    red: "#fc4384"
    green: "#b3e33b"
    yellow: "#ffa727"
    blue: "#75dff2"
    magenta: "#ae89fe"
    cyan: "#708387"
    white: "#d5d5d0"
    brightBlack: "#626566"
    brightRed: "#ff7fac"
    brightGreen: "#c8ed71"
    brightYellow: "#ebdf86"
    brightBlue: "#75dff2"
    brightMagenta: "#ae89fe"
    brightCyan: "#b1c6ca"
    brightWhite: "#f9f9f4"
  
# Records, feel free to edit them
records:
  - delay: 1110
    content: "\e]0;fish /home/yuki/.local/src/github.com/acomagu/fish-async-prompt\a\e[30m\e(B\e[mWelcome to fish, the friendly interactive shell\r\n"
  - delay: 6
    content: "\e[?2004h"
  - delay: 43
    content: "\e]0;fish /home/yuki/.local/src/github.com/acomagu/fish-async-prompt\a\e[30m\e(B\e[m\e[2m⏎\e(B\e[m                                                                                                                                                                                     \r⏎ \r\e[K\e[36m ❯\e[36m❯ \e[30m\e(B\e[m\e[K"
  - delay: 561
    content: "l\b\e[38;2;255;0;0ml\e[30m\e(B\e[m\e[38;2;85;85;85ms\b\e[30m\e(B\e[m"
  - delay: 38
    content: "\e[38;2;255;0;0ms\e[30m\e(B\e[m\b\b\e[38;2;255;255;255mls\e[30m\e(B\e[m"
  - delay: 392
    content: "\r\n\e[30m\e(B\e[m"
  - delay: 116
    content: "\e[?2004l\e]0;ls /home/yuki/.local/src/github.com/acomagu/fish-async-prompt\a\e[30m\e(B\e[m\r"
  - delay: 9
    content: "async-prompt.yml  \e[0m\e[01;34mconf.d\e[0m/  \e[01;35mdemo.svg\e[0m  README.md  \e[01;35mrender1567120785334.gif\e[0m  \e[01;35mrender1567122124352.gif\e[0m  test-fish.yml\r\n"
  - delay: 6
    content: "\e[?2004h\e]0;fish /home/yuki/.local/src/github.com/acomagu/fish-async-prompt\a\e[30m\e(B\e[m\e[2m⏎\e(B\e[m                                                                                                                                                                                     \r⏎ \r\e[K\e[36m ❯\e[36m❯ \e[30m\e(B\e[m\e[K\e[143C\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[4C"
  - delay: 6
    content: "\e]0;fish /home/yuki/.local/src/github.com/acomagu/fish-async-prompt\a\e[30m\e(B\e[m\r\e[36m ❯\e[36m❯ \e[30m\e(B\e[m\e[K\e[143C\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[4C"
  - delay: 991
    content: "\e]0;fish /home/yuki/.local/src/github.com/acomagu/fish-async-prompt\a\e[30m\e(B\e[m\r\e[36m ❯\e[36m❯ \e[30m\e(B\e[m\e[K\e[143C\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[4C"
  - delay: 168
    content: "e\e[142C\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[5C\e[142C\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[5C\b\e[38;2;255;0;0me\e[142C\e[30m\e(B\e[m\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[5C\e[38;2;85;85;85mxit\e[139C\e[30m\e(B\e[m\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[5C"
  - delay: 135
    content: "\e[38;2;255;0;0mx\e[38;2;85;85;85mit\e[139C\e[30m\e(B\e[m\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[6C\e[141C\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[6C\b\b\e[38;2;255;255;255mex\e[38;2;85;85;85mit\e[139C\e[30m\e(B\e[m\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[6C"
  - delay: 113
    content: "\e[38;2;255;255;255mi\e[38;2;85;85;85mt\e[139C\e[30m\e(B\e[m\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[7C\e[140C\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[7C\b\b\b\e[38;2;255;0;0mexi\e[38;2;85;85;85mt\e[139C\e[30m\e(B\e[m\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[7C"
  - delay: 13
    content: "\e[38;2;255;0;0mt\e[139C\e[30m\e(B\e[m\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[8C\e[139C\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[8C\b\b\b\b\e[38;2;255;255;255mexit\e[139C\e[30m\e(B\e[m\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[8C"
  - delay: 206
    content: "\e[139C\e[93mmaster \e[36m~/.l/s/g/a/fish-async-prompt\r\e[147C\r\e[8C\r\n\e[30m\e(B\e[m\e[?2004l\e]0;exit /home/yuki/.local/src/github.com/acomagu/fish-async-prompt\a\e[30m\e(B\e[m\r\e[30m\e(B\e[m\e[?2004l"
```

</details>
