### ISSUE TITLE
Support for ANSI escape codes?

### ISSUE THREAD

**Issue by chris-hailstorm** [faressoft/terminalizer#51]
I use ANSI escape codes in my prompt:

    $ echo $PS1
    \[\033[7m\][\u - \w]\[\033[0m\] $

This creates a prompt with reverse video.

When I record a session using terminalizer, the prompt is captured like this:

    content: "\e[7m[cjohnson - ~/proj/docker1]\e[0m $ "

And when I render this, it comes through as a solid block of white (characters not visible).

Can you suggest how to capture and render this -- special considerations for ANSI codes?

**Comment by faressoft** [comment]
Could you please provide your recording an a screenshot

**Comment by urbanadventurer** [comment]
I can confirm this issue with terminalizer v0.6.1 when using a theme that has the background set to "transparent".

```yml
theme:
  background:  "transparent" 
  foreground: "#afafaf" 
  cursor: "#c7c7c7"
  black: "#161616"
```

To demonstrate it I made a recording of the following command. The ANSI escape sequences are RED, REVERSE, NORMAL, GREEN, REVERSE.
```
echo -e "\033[0;31myi\033[1;7myo"; echo -e "\033[0;0m"; echo -e "\u001b[32mhi\u001b[7mho"
```

![render1574091383289](https://user-images.githubusercontent.com/101783/69066581-f4395380-0a3a-11ea-9159-cfffcbe1045d.gif)

The behavior changes if I set the background to another color.

```yml
theme:
  background: "#161616" 
  foreground: "#afafaf" 
  cursor: "#c7c7c7"
  black: "#161616"
```


![render1574092018704](https://user-images.githubusercontent.com/101783/69067311-48910300-0a3c-11ea-8488-713c2f017939.gif)
