### ISSUE TITLE
Custom background color for recorded files

### ISSUE THREAD

**Issue by MaximDevoir** [faressoft/terminalizer#61]
**Issue**
Currently, the background of rendered Terminalizer recordings are white. This imposes design restrictions on how we can display the recordings/gifs to the user.

**Question**
Is there an option to set the background color behind the rendered terminal?

**Example**
Demonstration of the issue achieved by setting the `background` color on the [Terminalizer GitHub](https://github.com/faressoft/terminalizer) repository page to a non-`#FFF` color.
 
![Screenshot from 2019-08-15 20-16-30](https://user-images.githubusercontent.com/10104630/63141174-9d366500-bf99-11e9-8af1-354b260e336d.png)

**Comment by jasonhodges** [comment]
☝️

**Comment by voodoomm** [comment]
The work-around is to specify a negative margin or use the boxShadow to set the background.  That's been sufficient for my needs.
````
frameBox:
  type: floating
  title: PowerShell
  style:
    border: 2px solid cornflowerblue
    boxShadow: 0px 0px 0px 20px blue
    margin: 10px
````
![term](https://user-images.githubusercontent.com/20617321/70093431-03490580-15e6-11ea-8493-9312539abb19.png)
