### ISSUE TITLE
No cursor and missalignment with zsh and Meslo LG S for Powerline font

### ISSUE THREAD

**Issue by ericbn** [faressoft/terminalizer#81]
This is how I recorded and rendered the recording:
```
% node --version
v10.17.0
% terminalizer record -c config.yml myrec
The recording session is started
Press CTRL+D to exit and save the recording
...
% terminalizer render myrec
Rendering frame 6/6 100% [==============================] 0.0s
Merging frame 6/6 100% [==============================] 0.0s

Successfully Rendered
...
```

Here's the generated myrec.yml:

```
config:
  command: zsh  
  cwd: /path/to/home  
  env:
    recording: true  
  cols: 87  
  rows: 4  
  repeat: 0  
  quality: 100  
  frameDelay: auto  
  maxIdleTime: 2000  
  frameBox:
    type: solid
    title: null
    style:
      border: 0px black solid
      boxShadow: none
      margin: 2px 5px  
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9  
  cursorStyle: block  
  fontFamily: "Meslo LG S for Powerline"  
  fontSize: 14  
  lineHeight: 1  
  letterSpacing: 0  
  theme:
    background: "#000000"
    foreground: "#c7c7c7"
    cursor: "#c7c7c7"
    black: "#000000"
    red: "#c91b00"
    green: "#00c200"
    yellow: "#c7c400"
    blue: "#0225c7"
    magenta: "#c930c7"
    cyan: "#00c5c7"
    white: "#c7c7c7"
    brightBlack: "#676767"
    brightRed: "#ff6d67"
    brightGreen: "#5ff967"
    brightYellow: "#fefb67"
    brightBlue: "#6871ff"
    brightMagenta: "#ff76ff"
    brightCyan: "#5ffdff"
    brightWhite: "#feffff"  
records:
  - delay: 1166
    content: "\e]1337;RemoteHost=user@host.local\a\e]1337;CurrentDir=/path/to/home\a\e]1337;ShellIntegrationVersion=6;shell=zsh\a"
  - delay: 368
    content: "\e[1m\e[7m%\e[27m\e[1m\e[0m                                                                                      \r \r"
  - delay: 35
    content: "\e]133;D;0\a\e]1337;RemoteHost=user@host.local\a\e]1337;CurrentDir=/path/to/home\a"
  - delay: 10
    content: "\r\e[0m\e[27m\e[24m\e[J\e]133;A\a\e[7m\e[34m ~ \e[27m\e[34m\e[49m\e[34m\e[39m \e]133;B\a\e[K\e[?1h\e=\e[?2004h"
  - delay: 733
    content: "\e[32mexit\e[39m\b\e[32mt\e[27m\e[39m"
  - delay: 121
    content: "\b\e[32mt\e[39m\e[?1l\e>\e[?2004l\r\r\n\e]133;C;\a"
```

And this is the render result:

![render1577931233199](https://user-images.githubusercontent.com/4120606/71649408-81c7be80-2cdc-11ea-9abb-a3378008383c.gif)

This is what I was expecting, in terms of margins, alignment of the line with the standout mode and the Powerline glyph, and having a cursor (static image):

![Screen Shot 2020-01-01 at 21](https://user-images.githubusercontent.com/4120606/71649595-2c8cac80-2cde-11ea-8036-54e4e266fbb1.png)
